### ISSUE TITLE
主人无法执行命令，无法设置多个主人

### ISSUE THREAD

**Issue by kroazi** [Proviasw/nonebot-plugin-mcport#3]
06-30 21:28:13 [INFO] nonebot-plugin-mcport | 有人触发"执行命令"指令了哦~
06-30 21:28:13 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-mcport.mcrcon) running complete
06-30 21:28:13 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-mcport.mcrcon) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot-plugin-mcport/mcrcon.py", line 57, in mingling
    async with MinecraftClient(rconhost, rconport, rconpassword) as mc:
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/async_mcrcon/async_mcrcon.py", line 24, in __aenter__
    await self._authenticate()
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/async_mcrcon/async_mcrcon.py", line 34, in _authenticate
    await self._send(3, self.password)
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/async_mcrcon/async_mcrcon.py", line 61, in _send
    raise InvalidPassword('Incorrect password.')
async_mcrcon.async_mcrcon.InvalidPassword: Incorrect password.

这是控制台输出
非主人有交互 主人会出现报错

**Comment by TissyBoxC** [comment]
你好，看看.env配置项谢谢

**Comment by TissyBoxC** [comment]
按照这个格式写就没问题zr=[122, 123]
